import { StyleSheet } from '@react-pdf/renderer'

export const professionalTemplateStyles = StyleSheet.create({
    page: {
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 15,
        paddingRight: 15,
        fontSize: 10,
        fontFamily: 'Helvetica',
        backgroundColor: '#ffffff',
        position: 'relative',
    },
    watermark: {
        position: 'absolute',
        top: '35%',
        left: '20%',
        width: '60%',
        textAlign: 'center',
    },
    watermarkText: {
        fontSize: 90,
        fontWeight: 'bold',
        color: '#d1d5db',
        opacity: 0.15,
        letterSpacing: 10,
    },
    content: {
        position: 'relative',
        zIndex: 1,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        borderBottom: 2,
        borderBottomColor: '#000000',
        paddingBottom: 10,
    },
    logo: {
        width: 80,
        height: 80,
        objectFit: 'contain',
    },
    shopNameAddress: {
        flex: 1,
        paddingHorizontal: 20,
        textAlign: 'left',
    },
    shopInfo: {
        textAlign: 'right',
    },
    shopName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 4,
    },
    shopDetail: {
        fontSize: 9,
        color: '#4b5563',
        marginBottom: 2,
    },
    invoiceTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 8,
    },
    section: {
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    column: {
        width: '48%',
    },
    columnThree: {
        width: '32%',
    },
    label: {
        fontSize: 8,
        color: '#6b7280',
        marginBottom: 2,
        textTransform: 'uppercase',
    },
    value: {
        fontSize: 10,
        color: '#111827',
        fontWeight: 'bold',
    },
    table: {
        marginTop: 10,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#000000',
        padding: 6,
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 9,
    },
    tableRow: {
        flexDirection: 'row',
        borderBottom: 1,
        borderBottomColor: '#e5e7eb',
        padding: 6,
        fontSize: 9,
    },
    tableRowAlt: {
        backgroundColor: '#f9fafb',
    },
    col1: { width: '40%' },
    col2: { width: '15%', textAlign: 'center' },
    col3: { width: '15%', textAlign: 'center' },
    col4: { width: '15%', textAlign: 'right' },
    col5: { width: '15%', textAlign: 'right' },
    totalsSection: {
        marginTop: 15,
        alignItems: 'flex-end',
    },
    totalsBox: {
        width: '40%',
        borderTop: 2,
        borderTopColor: '#000000',
        paddingTop: 8,
    },
    totalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    totalLabel: {
        fontSize: 10,
        color: '#4b5563',
    },
    totalValue: {
        fontSize: 10,
        color: '#111827',
        fontWeight: 'bold',
    },
    grandTotal: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 6,
        paddingTop: 6,
        borderTop: 1,
        borderTopColor: '#d1d5db',
    },
    grandTotalLabel: {
        fontSize: 12,
        fontWeight: 'bold',
        color: '#000000',
    },
    grandTotalValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#000000',
    },
    notes: {
        marginTop: 15,
        padding: 10,
        backgroundColor: '#f3f4f6',
        borderRadius: 4,
    },
    notesTitle: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#374151',
        marginBottom: 4,
    },
    notesText: {
        fontSize: 9,
        color: '#6b7280',
        lineHeight: 1.4,
    },
    footer: {
        position: 'absolute',
        bottom: 20,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 8,
        color: '#9ca3af',
        borderTop: 1,
        borderTopColor: '#e5e7eb',
        paddingTop: 8,
    },
    statusBadge: {
        padding: 4,
        borderRadius: 4,
        fontSize: 9,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    statusPaid: {
        backgroundColor: '#808080',
        color: '#ffffff',
    },
    statusPartiallyPaid: {
        backgroundColor: '#a0a0a0',
        color: '#ffffff',
    },
    statusUnpaid: {
        backgroundColor: '#606060',
        color: '#ffffff',
    },
    paymentInfo: {
        marginTop: 8,
        padding: 8,
        backgroundColor: '#f9fafb',
        borderRadius: 4,
    },
    paymentHistory: {
        marginTop: 10,
    },
    paymentHistoryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 4,
        borderBottom: 1,
        borderBottomColor: '#e5e7eb',
    },
    paymentHistoryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 6,
        borderBottom: 2,
        borderBottomColor: '#000000',
        marginBottom: 4,
    },
    paymentHistoryHeaderText: {
        fontSize: 9,
        fontWeight: 'bold',
        color: '#000000',
        textTransform: 'uppercase',
    },
    workOrderSection: {
        marginBottom: 15,
        padding: 10,
        backgroundColor: '#f3f4f6',
        borderRadius: 4,
    },
    workOrderTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 4,
    },
    workOrderDescription: {
        fontSize: 9,
        color: '#4b5563',
        lineHeight: 1.4,
    },
    vehicleInfoRow: {
        marginBottom: 3,
    },
})
