'use client'

import { useState, useMemo } from "react";
import { Nav } from "@/app/components/nav";
import { WorkOrderKanban, WorkOrderHeader } from "../components/work-orders";
import { WorkOrderDetailsModal, WorkOrderCreateModal } from "../components/work-orders/WorkOrderModal";
import { useWorkOrderStats } from "../hooks/use-work-order-stats";
import { useWorkOrders, useCreateWorkOrder } from "../hooks/use-work-orders";
import { useAuth } from "../hooks/use-auth";
import type { WorkOrderKanbanColumn, WorkOrderKanbanItem } from "../types/work-order";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2, AlertCircle } from "lucide-react";
import type { WorkOrder } from "../types/work-order";

// Helper function to transform WorkOrder to WorkOrderKanbanItem
function transformWorkOrderToKanbanItem(workOrder: WorkOrder): WorkOrderKanbanItem {
    return {
        id: workOrder.id,
        title: workOrder.title,
        description: workOrder.description,
        priority: workOrder.priority,
        assignee: workOrder.assigned_technician_id, // TODO: Map to actual technician name
        date: workOrder.due_date || workOrder.created_at.split('T')[0],
        customer: "Loading...", // TODO: Fetch customer name from customer_id
        vehicle: "Loading...", // TODO: Fetch vehicle info from vehicle_id  
        tags: workOrder.tags || []
    }
}

export default function WorkOrdersPage() {
    // Authentication
    const { user, shopId, isLoading: authLoading, error: authError } = useAuth()
    
    // Data fetching - only fetch if we have a valid shopId
    const { data: workOrders, isLoading: workOrdersLoading, error: workOrdersError, refetch } = useWorkOrders(shopId || '')
    const createWorkOrderMutation = useCreateWorkOrder()
    
    // Combined loading state
    const isLoading = authLoading || (shopId && workOrdersLoading)
    // Combined error state
    const error = authError || workOrdersError
    
    // Transform work orders to kanban format
    const kanbanData = useMemo(() => {
        if (!workOrders) return []
        
        const pending = workOrders.filter(wo => wo.status === 'pending' || wo.status === 'approved')
        const inProgress = workOrders.filter(wo => wo.status === 'in_progress' || wo.status === 'waiting_parts' || wo.status === 'waiting_customer')
        const completed = workOrders.filter(wo => wo.status === 'completed' || wo.status === 'invoiced')
        
        return [
            {
                id: 'pending',
                title: 'Estimates',
                color: 'bg-yellow-500',
                items: pending.map(transformWorkOrderToKanbanItem)
            },
            {
                id: 'in-progress',
                title: 'In Progress', 
                color: 'bg-blue-500',
                items: inProgress.map(transformWorkOrderToKanbanItem)
            },
            {
                id: 'completed',
                title: 'Completed',
                color: 'bg-green-500',
                items: completed.map(transformWorkOrderToKanbanItem)
            }
        ]
    }, [workOrders])
    
    // Calculate stats using custom hook
    const stats = useWorkOrderStats(kanbanData)
    
    // Modal state
    const [selectedWorkOrder, setSelectedWorkOrder] = useState<WorkOrderKanbanItem | null>(null)
    const [isModalOpen, setIsModalOpen] = useState(false)
    const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
    
    // View state
    const [isCompactView, setIsCompactView] = useState(false)

    // Handle work order card clicks
    const handleCardClick = (item: WorkOrderKanbanItem) => {
        setSelectedWorkOrder(item)
        setIsModalOpen(true)
    }

    // Handle view toggle
    const handleToggleView = () => {
        setIsCompactView(prev => !prev)
    }

    // Handle new work order
    const handleNewWorkOrder = () => {
        setIsCreateModalOpen(true)
    }

    // Handle create modal close
    const handleCreateModalClose = () => {
        setIsCreateModalOpen(false)
    }

    // Handle work order creation
    const handleWorkOrderCreate = async (workOrderData: any) => {
        if (!shopId || !user) {
            console.error('Missing authentication data')
            return
        }

        try {
            // Transform the form data to work order format
            const workOrderPayload: Omit<WorkOrder, 'id' | 'created_at' | 'updated_at'> = {
                work_order_number: '', // Will be auto-generated by service
                title: workOrderData.title,
                description: workOrderData.description,
                status: 'pending',
                priority: workOrderData.priority,
                shop_id: shopId,
                customer_id: 'temp-customer-id', // TODO: Use selected customer ID
                vehicle_id: 'temp-vehicle-id', // TODO: Use selected vehicle ID
                created_by_user_id: user.id,
                is_warranty_work: false,
                is_insurance_claim: false,
                customer_waiting: false,
                requires_estimate: true,
                estimate_approved: false,
                tags: workOrderData.tags,
                due_date: workOrderData.date,
                internal_notes: workOrderData.notes,
                vehicle_mileage: parseFloat(workOrderData.vehicleMileage) || undefined,
            }
            
            await createWorkOrderMutation.mutateAsync(workOrderPayload)
            setIsCreateModalOpen(false)
        } catch (error) {
            console.error('Failed to create work order:', error)
            // Error handling is done in the mutation hook
        }
    }

    // Handle modal close
    const handleModalClose = () => {
        setIsModalOpen(false)
        setSelectedWorkOrder(null)
    }

    // Handle work order save
    const handleWorkOrderSave = (updatedWorkOrder: WorkOrderKanbanItem) => {
        console.log('Work order updated:', updatedWorkOrder)
        // TODO: Update the work order in the data source
        setIsModalOpen(false)
    }

    // Handle work order delete
    const handleWorkOrderDelete = (workOrderId: string) => {
        console.log('Work order deleted:', workOrderId)
        // TODO: Implement delete mutation
        setIsModalOpen(false)
    }

    // Loading state
    if (isLoading) {
        return (
            <div className="h-screen flex flex-col bg-[#0d0d0d]">
                <Nav />
                <div className="flex-1 flex items-center justify-center">
                    <Card className="bg-[#1a1a1a] border-[#2a2a2a]">
                        <CardContent className="flex items-center gap-4 p-6">
                            <Loader2 className="h-6 w-6 animate-spin text-blue-500" />
                            <div>
                                <p className="text-white font-medium">Loading Work Orders</p>
                                <p className="text-gray-400 text-sm">Fetching data from database...</p>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        )
    }

    // Error state
    if (error) {
        return (
            <div className="h-screen flex flex-col bg-[#0d0d0d]">
                <Nav />
                <div className="flex-1 flex items-center justify-center">
                    <Card className="bg-[#1a1a1a] border-[#2a2a2a]">
                        <CardContent className="flex items-center gap-4 p-6">
                            <AlertCircle className="h-6 w-6 text-red-500" />
                            <div>
                                <p className="text-white font-medium">Failed to Load Work Orders</p>
                                <p className="text-gray-400 text-sm mb-3">
                                    {error instanceof Error ? error.message : 'Unknown error occurred'}
                                </p>
                                <button 
                                    onClick={() => refetch()}
                                    className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded text-sm"
                                >
                                    Try Again
                                </button>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        )
    }

    // Don't render main content if we don't have authentication data
    if (!shopId || !user) {
        return (
            <div className="h-screen flex flex-col bg-[#0d0d0d]">
                <Nav />
                <div className="flex-1 flex items-center justify-center">
                    <Card className="bg-[#1a1a1a] border-[#2a2a2a]">
                        <CardContent className="flex items-center gap-4 p-6">
                            <AlertCircle className="h-6 w-6 text-yellow-500" />
                            <div>
                                <p className="text-white font-medium">Authentication Required</p>
                                <p className="text-gray-400 text-sm mb-3">
                                    Unable to access work orders. Please ensure you are logged in.
                                </p>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        )
    }

    return (
        <div className="h-screen flex flex-col bg-[#0d0d0d]">
            <Nav />
            <div className="flex-1 flex flex-col overflow-hidden">
                <WorkOrderHeader 
                    totalCount={stats.totalCount}
                    pendingCount={stats.pendingCount}
                    inProgressCount={stats.inProgressCount}
                    completedCount={stats.completedCount}
                    isCompactView={isCompactView}
                    onToggleView={handleToggleView}
                    onNewWorkOrder={handleNewWorkOrder}
                />
                <div className="flex-1 overflow-hidden">
                    <WorkOrderKanban 
                        columns={kanbanData}
                        onCardClick={handleCardClick}
                        isCompactView={isCompactView}
                    />
                </div>
            </div>

            {/* Work Order Details Modal */}
            {isModalOpen && selectedWorkOrder && (
                <WorkOrderDetailsModal
                    workOrder={selectedWorkOrder}
                    onClose={handleModalClose}
                    onSave={handleWorkOrderSave}
                    onDelete={handleWorkOrderDelete}
                />
            )}

            {/* Work Order Create Modal */}
            {isCreateModalOpen && (
                <WorkOrderCreateModal 
                    onClose={handleCreateModalClose}
                    onSave={handleWorkOrderCreate}
                />
            )}
        </div>
    )
}