import { toast } from 'sonner'
import { WorkOrderCreationService } from '../../lib/work-order-creation-service'
import {
    useCreateWorkOrderWithDependencies,
    useCreateWalkInWorkOrder,
    useUpdateWorkOrder,
    useUpdateWorkOrderStatus,
    useDeleteWorkOrder,
} from '../use-work-orders'
import type { WorkOrder, WorkOrderKanbanItem, WorkOrderWithDetails } from '../../types/work-order'
import type { User } from '@supabase/supabase-js'

/**
 * Custom hook for work order CRUD operations
 * Handles creation, updating, deletion, and completion of work orders
 */
export function useWorkOrderOperations(
    shopId: string | null,
    user: User | null,
    workOrders: WorkOrderWithDetails[] | undefined,
    refetch: () => void
) {
    const createWorkOrderMutation = useCreateWorkOrderWithDependencies()
    const createWalkInWorkOrderMutation = useCreateWalkInWorkOrder()
    const updateWorkOrderMutation = useUpdateWorkOrder()
    const updateWorkOrderStatusMutation = useUpdateWorkOrderStatus()
    const deleteWorkOrderMutation = useDeleteWorkOrder()

    /**
     * Handle work order creation
     */
    const handleWorkOrderCreate = async (workOrderData: any) => {
        if (!shopId || !user) {
            console.error('Missing authentication data')
            return
        }

        try {
            let newWorkOrder: WorkOrder

            // Check if this is a walk-in customer
            if (workOrderData.customerType === 'walk_in') {
                console.log('Creating walk-in work order')

                // Prepare walk-in work order payload
                const walkInPayload = {
                    workOrder: {
                        work_order_number: '', // Will be auto-generated by service
                        title: workOrderData.title,
                        description: workOrderData.description,
                        status: 'pending' as const,
                        priority: workOrderData.priority,
                        shop_id: shopId,
                        // Ensure selected/created vehicle is linked on create
                        vehicle_id: workOrderData.vehicleId || undefined,
                        assigned_technician_id: workOrderData.assigneeId || undefined,
                        tags: workOrderData.tags || [],
                        attachments: [],
                        notes: workOrderData.notes || undefined,
                    },
                    walkInVehicleInfo: workOrderData.walkInVehicleInfo
                }

                console.log('Creating walk-in work order with payload:', walkInPayload)
                newWorkOrder = await createWalkInWorkOrderMutation.mutateAsync(walkInPayload)
            } else {
                console.log('Creating registered customer work order')

                // Prepare the data structure for registered customer
                const payload = {
                    workOrder: {
                        work_order_number: '', // Will be auto-generated by service
                        title: workOrderData.title,
                        description: workOrderData.description,
                        status: 'pending' as const,
                        priority: workOrderData.priority,
                        shop_id: shopId,
                        assigned_technician_id: workOrderData.assigneeId || undefined,
                        tags: workOrderData.tags || [],
                        attachments: [],
                        notes: workOrderData.notes || undefined,
                        customer_type: 'registered' as const,
                        walk_in_vehicle_info: undefined,
                    },
                    customer: {
                        id: workOrderData.customerId === "new" ? undefined : workOrderData.customerId,
                        name: workOrderData.customer || 'Unknown Customer',
                        email: workOrderData.customerEmail || undefined,
                        phone: workOrderData.customerPhone || undefined,
                        address: workOrderData.customerAddress || undefined,
                    },
                    vehicle: {
                        id: workOrderData.vehicleId === "new" ? undefined : workOrderData.vehicleId,
                        year: workOrderData.vehicleYear || new Date().getFullYear().toString(),
                        make: workOrderData.vehicleMake || 'Unknown',
                        model: workOrderData.vehicleModel || 'Unknown',
                        color: workOrderData.vehicleColor || undefined,
                        vin: workOrderData.vehicleVin || undefined,
                        license_plate: workOrderData.vehicleLicensePlate || undefined,
                        mileage: workOrderData.vehicleMileage || undefined,
                    }
                }

                console.log('Creating work order with payload:', payload)
                newWorkOrder = await createWorkOrderMutation.mutateAsync(payload)
            }

            // Create all work order items using the service
            const totalItemsCreated = await WorkOrderCreationService.createAllWorkOrderItems(
                newWorkOrder.id,
                workOrderData
            )

            // Show success message with items count
            if (totalItemsCreated > 0) {
                toast.success(`Work order created with ${totalItemsCreated} items`)
            }
        } catch (error) {
            console.error('Failed to create work order:', error)
            // Error handling is done in the mutation hook
        }
    }

    /**
     * Handle work order save/update
     */
    const handleWorkOrderSave = async (updatedWorkOrder: WorkOrderKanbanItem, formData?: any) => {
        try {
            // Use the work order ID from the updated work order
            const workOrderId = updatedWorkOrder.id

            // Prepare the update data
            const updateData: Partial<WorkOrder> = {
                title: updatedWorkOrder.title,
                description: updatedWorkOrder.description,
                priority: updatedWorkOrder.priority,
                tags: updatedWorkOrder.tags,
            }

            // Include notes if provided in formData
            if (formData?.notes !== undefined) {
                updateData.notes = formData.notes
            }

            // Include other form fields if provided
            if (formData) {
                // Map assignee back to assigned_technician_id if it's a UUID
                if (formData.assigneeId) {
                    updateData.assigned_technician_id = formData.assigneeId
                }
            }

            await updateWorkOrderMutation.mutateAsync({
                id: workOrderId,
                data: updateData
            })

            // Refetch to get updated data
            refetch()
        } catch (error) {
            console.error('Failed to update work order:', error)
            // Error handling is done in the mutation hook
        }
    }

    /**
     * Handle work order deletion
     */
    const handleWorkOrderDelete = async (workOrderId: string) => {
        try {
            await deleteWorkOrderMutation.mutateAsync(workOrderId)
            refetch() // Refetch work orders to update the list
        } catch (error) {
            console.error('Failed to delete work order:', error)
            // Error handling is done in the mutation hook
        }
    }

    /**
     * Handle work order completion confirmation
     */
    const handleCompletionConfirm = async (
        completionWorkOrder: WorkOrderWithDetails | null,
        sendMessage: boolean,
        customMessage?: string,
        enableAutomatedMessages: boolean = true
    ) => {
        if (!completionWorkOrder) return

        try {
            // Use updateWorkOrderStatus to trigger automated messaging
            // Pass enableAutomatedMessages flag to control whether automated messages are queued
            await updateWorkOrderStatusMutation.mutateAsync({
                id: completionWorkOrder.id,
                status: 'completed',
                enableAutomatedMessages
            })

            // Refetch work orders
            refetch()
        } catch (error) {
            console.error('Failed to complete work order:', error)
        }
    }

    return {
        handleWorkOrderCreate,
        handleWorkOrderSave,
        handleWorkOrderDelete,
        handleCompletionConfirm,
        isCreating: createWorkOrderMutation.isPending || createWalkInWorkOrderMutation.isPending,
        isUpdating: updateWorkOrderMutation.isPending || updateWorkOrderStatusMutation.isPending,
        isDeleting: deleteWorkOrderMutation.isPending,
    }
}
