export type OEMBrand =
    | 'chrysler' | 'ford' | 'gm' | 'honda' | 'hyundai' | 'jaguar'
    | 'land-rover' | 'mazda' | 'mitsubishi' | 'nissan' | 'subaru'
    | 'toyota' | 'volkswagen' | 'volvo'

/**
 * OEM-specific copyright notices that must be displayed when using data from each manufacturer.
 * Customer agrees to place these notices in a prominent fashion on any product that incorporates MOTOR Database(s).
 */
export const OEM_COPYRIGHTS: Record<OEMBrand, string> = {
    chrysler: "Portions of materials contained herein are sourced by FCA US, LLC.",
    ford: "This product contains copyrighted and other protected material owned by FORD Motor Company. Unauthorized use or reproduction, in whole or in part, is prohibited.",
    gm: "Portions of materials contained herein have been reprinted under license from General Motors, LLC, License Agreement #2310717, as amended or superseded.",
    honda: "Portions of materials contained herein have been reprinted under license from American Honda Corporation, License Agreement 16203AH. The catalog and data included herein cannot be reproduced without the prior written consent of American Honda Motor Co., Inc. Subscriber acknowledges that American Honda Motor Co is the owner or exclusive licensee of Honda information and the Honda trademarks.",
    hyundai: "Portions of materials contained herein have been reprinted under license from Hyundai Motor America, License Agreement HMA20004. All copyrights in and to such material are owned by Hyundai Motor America. © 2025 HMA",
    jaguar: "This product contains material that is reproduced and distributed under a license from Jaguar Cars Limited. No further reproduction or distribution of the Jaguar material is allowed without the express written permission of Jaguar Cars Limited. The recommended times for the repairs described in this publication with respect to Jaguar branded products are not based solely upon time studies conducted by Jaguar Cars Limited. The repair times it recommends to its franchised dealers for warranty repairs are based on time studies of the diagnostic and repair procedures it conducts and publishes in Jaguar service manuals. Accordingly, the recommended repair times specified in this publication are designed for aftermarket repairs only.",
    'land-rover': "This product contains material that is reproduced and distributed under a license from Land Rover. No further reproduction or distribution of the Land Rover material is allowed without the express written permission of Land Rover. The recommended times for the repairs described in this publication with respect to Land Rover branded products are not based solely upon time studies conducted by Land Rover. The repair times it recommends to its franchised dealers for warranty repairs are based on time studies of the diagnostic and repair procedures it conducts and publishes in Land Rover service manuals. Accordingly, the recommended repair times specified in this publication are designed for aftermarket repairs only.",
    mazda: "This product contains copyrighted and other protected material owned by Mazda North America. Unauthorized use or reproduction, in whole or in part, is prohibited.",
    mitsubishi: "Portions of materials contained herein have been reprinted under license from MITSUBISHI MOTORS NORTH AMERICA, INC.",
    nissan: "Portions of materials contained herein have been reprinted under a license from Nissan North America (license Agreement NNA15007). Unauthorized user or reproduction, in whole or in part, is prohibited.",
    subaru: "Portions of materials contained herein have been reprinted under license from Subaru of America, Inc. This product contains material that is reproduced and distributed under a license from Subaru of America, Inc. No further reproduction or distribution of the Subaru material is allowed without the express written permission of Subaru of America, Inc. Customer may only use, market, advertise, sell, or distribute (\"Distribute\") Subaru data only to End Users in the North American Market. \"North American Market\" is defined as the United States of America (inclusive of Guam, Puerto Rico, and the U.S. Virgin Islands, but excluding other U.S. Territories) and excludes Canada and Mexico and, if applicable, refrain from selling Subaru data to persons or entities who intend or are likely to Distribute it in any geographic area outside of the North American Market.",
    toyota: "Portions of materials contained herein have been included under license from Toyota Motor Sales, U.S.A., Inc. License Agreement TMS1008. Please see https://www.motor.com/oem-compliance-requirements for important disclosures regarding these materials. The Toyota Copyright Notice above must be displayed in a readily identifiable location and in at least the same size and prominence as other terms and conditions, (i) on LICENSEE's web page from which LICENSED WORKS may be downloaded, (ii) in a prominent location in LICENSED WORKS that are printed publications, and (iii) on LICENSEE'S terms and conditions of service agreed to by all users of LICENSED WORKS. Materials Included Under License from Toyota Motor Sales, U.S.A., Inc. License Agreement TMS1008. All information contained in any materials obtained about Toyota, Lexus, and Scion vehicles is based on the latest product information available at the time of publication, is provided \"as is\" without warranty of any kind, and is intended for service providers and other interested parties in Canada, Mexico, and the United States of America, including Guam, Puerto Rico, and the U.S. Virgin Islands. Specifications and procedures are subject to change without notice. This information is provided expressly for the purpose of use by professional automobile technicians who have special techniques and certifications. Repair or service by non-specialized or uncertified technicians using only this information, or without proper equipment or tools, may cause severe injury to the individual or other individuals and could possibly cause damage to the vehicle. Certain procedures or content elements may make reference to Toyota Warranty policy or practice – these policies or practices are only applicable to Toyota, Lexus, or Scion dealers.",
    volkswagen: "Portions of materials contained herein have been reprinted under license from Volkswagen Group of America, Inc., License Agreement 15500VWA.",
    volvo: "This product contains material that is reproduced and distributed under a license from Volvo Car Corporation. No further reproduction or distribution of the Volvo material is allowed without the express written permission of Volvo Car Corporation. The recommended times for the repairs described in this publication with respect to Volvo branded products are not based solely upon time studies conducted by Volvo Car Corporation. The repair times it recommends to its franchised dealers for warranty repairs are based on time studies of the diagnostic and repair procedures it conducts and publishes in Volvo service manuals. Accordingly, the recommended repair times specified in this publication are designed for aftermarket repairs only.",
}

/**
 * General MOTOR terms and conditions that apply to all OEM data usage
 */
export const MOTOR_GENERAL_TERMS = {
    Affiliation: "MOTOR is an independent business and is not sponsored by or affiliated with any OEM. Customer acknowledges that OEMs are not responsible for any goods or services provided to Customer by MOTOR",
    Advertising_Content: "Customer shall not, without OEM's prior review and express written consent, issue any press release, or issue or make any other public comment, or publish or broadcast any advertisement in any media, or disseminate any sales promotion materials, regarding its relationship with OEM. As soon as practicable after receiving such notice, OEM will either consent to the issuance of the proposed statement, advertisement or sales promotion materials or advise Customer of its objections thereto. OEM will discuss any such objections in good faith.",
    Reputation: "Customer will not engage, participate or otherwise become involved in any activity or course of action that diminishes or tarnishes the image or reputation of any of the Database(s).",
    Third_Party_Beneficiary: "Any OEM with data included in the Database(s) is an express third party beneficiary entitled to enforce terms outlined in this Agreement.",
    Quality_Standards: "Customer covenants and warrants that the Product(s) sold or distributed by it shall be of a high standard of style, appearance and quality, shall be fit for their intended use, and shall be consistent with industry standards. Customer agrees that the Product shall meet or exceed any and all standards, regulations, guidelines, rules, laws, and the like in the Territory relating to materials similar to the Product.",
    Liabilities: "Any approval by OEM of any Product will not give rise to obligations or liability to OEM. Customer will not have any rights against OEM for damages or other remedy by reason of OEM failure or refusal to grant access to the Database(s).",
    Product_Samples: "Upon request, Customer shall furnish free of charge for any OEM's review and approval samples of (i) all advertising based upon the Database(s); (ii) the intended uses of the Database(s) by Customer in conjunction with the Product; and/or (iii) all packaging, labeling, point of sale materials, trade show displays, and sales materials containing, referencing or based upon the Database(s). Customer shall expressly grant to each OEM a non-exclusive, non-transferable, paid-up royalty-free, license, with no rights to sublicense to others, except to certain but not limited to such OEM's affiliated companies to access, review, print, display and distribute for internal purposes only such Product or any portions thereof that such Customer creates or has created on its behalf for the sole purpose of determining the compliance of such Product with the terms of this Agreement. This includes no cost subscriptions of all Products to an OEM or its affiliated companies solely to determine compliance with the terms of this Agreement. Customer agrees to provide instructions to the OEM requesting the access to such Product for review upon request. In addition, Customer agrees, upon request, to provide a Product demonstration via WebEx or equivalent.",
    Copyright_Notices: "Customer agrees to place the following OEM Copyright Notices in a prominent fashion on any product sold or distributed by the Customer that incorporates any of the Database(s).",
} as const

export const OEM_COMPLIANCE_URL = "https://www.motor.com/oem-compliance-requirements/"
