
import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

function generateContractHTML(contract: any, shop: any) {
    const sections = contract.content?.map((section: any) => `
        <div style="margin-bottom: 20px;">
            <h2 style="font-size: 1.2em; border-bottom: 1px solid #eee; padding-bottom: 5px; margin-bottom: 10px;">${section.title}</h2>
            <p style="white-space: pre-wrap; line-height: 1.6;">${section.content}</p>
        </div>
    `).join('') || '';

    return `
        <!DOCTYPE html>
        <html>
        <body style="font-family: Arial, sans-serif; color: #333;">
            <div style="max-width: 800px; margin: auto; padding: 20px; border: 1px solid #ddd;">
                <div style="text-align: center; margin-bottom: 30px;">
                    <h1 style="font-size: 2em;">${contract.title}</h1>
                    <p>Between ${shop.shop_name} and the customer.</p>
                </div>
                ${sections}
                <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; font-size: 0.9em; color: #777;">
                    <p>This contract was generated by ${shop.shop_name}.</p>
                    <p>${shop.shop_address || ''}</p>
                </div>
            </div>
        </body>
        </html>
    `;
}

export async function POST(request: Request) {
    const supabase = createRouteHandlerClient({ cookies });
    const { contractId, customerEmail } = await request.json();

    try {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { data: userData } = await supabase.from('users').select('shop_id').eq('id', session.user.id).single();
        if (!userData?.shop_id) {
            return NextResponse.json({ error: 'Shop not found' }, { status: 404 });
        }
        
        const { data: contract, error: contractError } = await supabase
            .from('service_contracts')
            .select('*')
            .eq('id', contractId)
            .eq('shop_id', userData.shop_id)
            .single();

        if (contractError || !contract) {
            return NextResponse.json({ error: 'Contract not found' }, { status: 404 });
        }

        const { data: shop, error: shopError } = await supabase
            .from('shops')
            .select('*')
            .eq('id', userData.shop_id)
            .single();
            
        if (shopError || !shop) {
            return NextResponse.json({ error: 'Shop data not found' }, { status: 404 });
        }
        
        await resend.emails.send({
            from: `MotorMinds <noreply@${process.env.EMAIL_DOMAIN}>`,
            to: customerEmail,
            subject: `Service Contract from ${shop.shop_name}: ${contract.title}`,
            html: generateContractHTML(contract, shop),
        });

        // Optionally, update the contract status to 'sent'
        await supabase
            .from('service_contracts')
            .update({ status: 'sent' })
            .eq('id', contractId);

        return NextResponse.json({ message: 'Email sent successfully' });

    } catch (error: any) {
        console.error("Send email error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
} 